Increase compatibility with python3 installs in push hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -51,4 +51,12 @@ do
 done
 
 python3 -m robotpy test || exit 1
+if [$? -ne 0]; then
+	echo "python3 not found or tests failed, trying py3"
+	py3 -m robotpy test || exit 1
+	if [ $? -ne 0 ]; then
+		echo "py3 not found or tests failed"
+		exit 1
+	fi
+fi
 exit 0
